# -*- coding: utf-8 -*-
"""Endo_CDSS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AjXGZE8CjDww85rRNs37B5deCd7tzDPJ
"""

!pip install -q gradio openai-whisper torch

import gradio as gr
import whisper
import json
import re

model = whisper.load_model("base")
print("Whisper model loaded successfully.")

def determine_tooth_type(tooth_number):

    if tooth_number is None:
        return None

    # Anteriors
    if tooth_number in [6,7,8,9,10,11,22,23,24,25,26,27]:
        return "Anterior"

    # Premolars
    if tooth_number in [4,5,12,13,20,21,28,29]:
        return "Premolar"

    # Molars
    return "Molar"

def normalize_text(text):

    text = text.lower()

    replacements = {
        # Vitality variations
        "non-vital": "non vital",
        "nonvital": "non vital",
        "failed vitality": "non vital",
        "does not respond to cold": "no response",
        "no response to cold": "no response",
        "no response to vitality": "no response",

        # Cold test variations
        "lingers": "lingering",
        "lingered": "lingering",

        # Radiographic variations
        "periapical radiolucency": "radiolucency",
        "pa radiolucency": "radiolucency",

        # Sinus tract variations
        "draining sinus": "sinus tract",
        "fistula": "sinus tract",

        # Spontaneous pain variations
        "pain at night": "spontaneous pain",
        "pain without stimulus": "spontaneous pain"
    }

    for key, value in replacements.items():
        text = text.replace(key, value)

    return text

def extract_structured_data(text):

    text_lower = normalize_text(text)

    data = {
        "age": None,
        "tooth_number": None,
        "cold_response": None,
        "no_cold_response": False,
        "percussion": False,
        "swelling": False,
        "fever": False,
        "diabetes": False,
        "radiolucency": False,
        "radiopacity": False,
        "sinus_tract": False,
        "discoloration": False,
        "spontaneous_pain": False
    }

    # Age
    age_match = re.search(r"\b(\d{2})\s*year", text_lower)
    if age_match:
        data["age"] = int(age_match.group(1))

    # Tooth number
    tooth_match = re.search(r"#(\d{1,2})", text_lower)
    if tooth_match:
        tooth = int(tooth_match.group(1))
        if 1 <= tooth <= 32:
            data["tooth_number"] = tooth

    # Cold tests
    if "lingering" in text_lower:
        data["cold_response"] = "lingering"
    elif "short" in text_lower:
        data["cold_response"] = "short"

    if "no response" in text_lower or "non vital" in text_lower:
        data["no_cold_response"] = True

    # Clinical findings
    if "percussion" in text_lower:
        data["percussion"] = True

    if "swelling" in text_lower:
        data["swelling"] = True

    if "fever" in text_lower:
        data["fever"] = True

    if "diabetes" in text_lower:
        data["diabetes"] = True

    if "radiolucency" in text_lower:
        data["radiolucency"] = True

    if "radiopacity" in text_lower or "condensing osteitis" in text_lower:
        data["radiopacity"] = True

    if "sinus tract" in text_lower:
        data["sinus_tract"] = True

    if "discoloration" in text_lower:
        data["discoloration"] = True

    if "spontaneous pain" in text_lower:
        data["spontaneous_pain"] = True

    return data

def pulpal_diagnosis(data):

    reasoning = []
    diagnosis = "Normal Pulp"

    if data["cold_response"] == "short" and not data["spontaneous_pain"]:
        diagnosis = "Reversible Pulpitis"
        reasoning.append("Short cold response without spontaneous pain.")

    elif data["cold_response"] == "lingering" or data["spontaneous_pain"]:
        diagnosis = "Symptomatic Irreversible Pulpitis"
        reasoning.append("Lingering cold response or spontaneous pain.")

    elif data["no_cold_response"]:
        diagnosis = "Pulp Necrosis"
        reasoning.append("Non-vital tooth indicates pulp necrosis.")

    return diagnosis, reasoning

def apical_diagnosis(data):

    reasoning = []
    diagnosis = "Normal Apical Tissues"

    # Priority order

    if data["swelling"] and data["fever"]:
        diagnosis = "Acute Apical Abscess"
        reasoning.append("Swelling with systemic involvement.")

    elif data["sinus_tract"]:
        diagnosis = "Chronic Apical Abscess"
        reasoning.append("Sinus tract indicates chronic apical abscess.")

    elif data["percussion"]:
        diagnosis = "Symptomatic Apical Periodontitis"
        reasoning.append("Percussion sensitivity present.")

    elif data["radiolucency"]:
        diagnosis = "Asymptomatic Apical Periodontitis"
        reasoning.append("Radiolucency without symptoms.")

    elif data["radiopacity"]:
        diagnosis = "Condensing Osteitis"
        reasoning.append("Radiopacity at apex.")

    return diagnosis, reasoning

def treatment_planner(pulp_dx, apical_dx, data):

    treatment = None
    cdt = None

    if pulp_dx == "Reversible Pulpitis":
        treatment = "Remove irritant + Restoration"
        cdt = "D2330"

    elif pulp_dx in ["Symptomatic Irreversible Pulpitis", "Pulp Necrosis"]:
        treatment = "Root Canal Therapy"
        tooth_type = determine_tooth_type(data["tooth_number"])

        if tooth_type == "Anterior":
            cdt = "D3310"
        elif tooth_type == "Premolar":
            cdt = "D3320"
        elif tooth_type == "Molar":
            cdt = "D3330"

    if apical_dx == "Acute Apical Abscess":
        treatment = "Incision and Drainage + Root Canal Therapy"
        cdt = "D7510"

    return treatment, cdt

def treatment_planner(pulp_dx, apical_dx, data):

    treatment = None
    cdt = None

    if pulp_dx == "Reversible Pulpitis":
        treatment = "Remove irritant + Restoration"
        cdt = "D2330"

    elif pulp_dx in ["Symptomatic Irreversible Pulpitis", "Pulp Necrosis"]:
        treatment = "Root Canal Therapy"
        tooth_type = determine_tooth_type(data["tooth_number"])

        if tooth_type == "Anterior":
            cdt = "D3310"
        elif tooth_type == "Premolar":
            cdt = "D3320"
        elif tooth_type == "Molar":
            cdt = "D3330"

    if apical_dx == "Acute Apical Abscess":
        treatment = "Incision and Drainage + Root Canal Therapy"
        cdt = "D7510"

    return treatment, cdt

def build_fhir_resources(data, pulp_dx, apical_dx, treatment, cdt):

    return {
        "Patient": {
            "resourceType": "Patient",
            "age": data["age"]
        },
        "PulpalCondition": {
            "resourceType": "Condition",
            "diagnosis": pulp_dx,
            "tooth": data["tooth_number"]
        },
        "ApicalCondition": {
            "resourceType": "Condition",
            "diagnosis": apical_dx,
            "tooth": data["tooth_number"]
        },
        "Procedure": {
            "resourceType": "Procedure",
            "procedure": treatment,
            "cdt_code": cdt
        }
    }

def process_input(audio, text_input):

    if audio:
        result = model.transcribe(audio)
        text = result["text"]
    else:
        text = text_input

    data = extract_structured_data(text)

    pulp_dx, pulp_reason = pulpal_diagnosis(data)
    apical_dx, apical_reason = apical_diagnosis(data)

    treatment, cdt = treatment_planner(pulp_dx, apical_dx, data)

    reasoning = pulp_reason + apical_reason

    fhir_output = build_fhir_resources(data, pulp_dx, apical_dx, treatment, cdt)

    return (
    "",  # transcript hidden
    str(data["tooth_number"]),
    pulp_dx,
    apical_dx,
    treatment,
    cdt,
    "\n".join(reasoning),
    json.dumps(fhir_output, indent=2)
)

def structured_process_input(
    age,
    tooth,
    endo_ice,
    lingering,
    caries_pulp,
    prev_initiated,
    prev_treated,
    control_response,
    percussion,
    swelling,
    sinus,
    radiolucency,
    radiopacity
):

    # Build data dictionary
    data = {
        "age": age,
        "tooth_number": tooth
    }

    reasoning = []

    # --------- PULPAL DIAGNOSIS ----------

    if prev_treated:
        pulp_dx = "Previously Treated"
        reasoning.append("Root canal previously completed.")

    elif prev_initiated:
        pulp_dx = "Previously Initiated Therapy"
        reasoning.append("Root canal previously initiated.")

    elif endo_ice == "Positive":

        if lingering:
            pulp_dx = "Symptomatic Irreversible Pulpitis"
            reasoning.append("Positive Endo Ice with lingering pain (>30s).")

        else:
            if caries_pulp:
                pulp_dx = "Asymptomatic Irreversible Pulpitis"
                reasoning.append("Vital pulp with caries into pulp but no lingering pain.")
            else:
                pulp_dx = "Reversible Pulpitis"
                reasoning.append("Positive Endo Ice without lingering pain.")

    elif endo_ice == "Negative":

        if control_response:
            pulp_dx = "Pulp Necrosis"
            reasoning.append("No response to Endo Ice while control tooth responds.")
        else:
            pulp_dx = "Inconclusive – Retest with EPT"
            reasoning.append("Control tooth also non-responsive. Further testing required.")

    else:
        pulp_dx = "Normal Pulp"
        reasoning.append("Normal vitality response.")

    # --------- APICAL DIAGNOSIS ----------

    if percussion:
        if swelling:
            apical_dx = "Acute Apical Abscess"
            reasoning.append("Percussion pain with swelling.")
        else:
            apical_dx = "Symptomatic Apical Periodontitis"
            reasoning.append("Percussion pain without swelling.")

    else:
        if sinus:
            apical_dx = "Chronic Apical Abscess"
            reasoning.append("Sinus tract present.")
        elif radiolucency:
            apical_dx = "Asymptomatic Apical Periodontitis"
            reasoning.append("Radiolucency without symptoms.")
        elif radiopacity:
            apical_dx = "Condensing Osteitis"
            reasoning.append("Periapical radiopacity present.")
        else:
            apical_dx = "Normal Apical Tissues"
            reasoning.append("No apical pathology detected.")

    # --------- TREATMENT TABLE ----------

    treatment_map = {
        "Normal Pulp": "No treatment",
        "Reversible Pulpitis": "Remove irritant + restoration",
        "Symptomatic Irreversible Pulpitis": "Root canal therapy",
        "Asymptomatic Irreversible Pulpitis": "Root canal therapy",
        "Pulp Necrosis": "Root canal therapy",
        "Previously Initiated Therapy": "Complete root canal therapy",
        "Previously Treated": "No treatment or evaluate for retreatment",
        "Symptomatic Apical Periodontitis": "Root canal therapy",
        "Asymptomatic Apical Periodontitis": "Root canal therapy",
        "Acute Apical Abscess": "Incision & drainage + root canal therapy",
        "Chronic Apical Abscess": "Debridement + root canal therapy",
        "Condensing Osteitis": "Treat pulpal cause"
    }

    treatment = treatment_map.get(pulp_dx, "")
    cdt = None

    if "Root canal" in treatment:
        tooth_type = determine_tooth_type(tooth)
        if tooth_type == "Anterior":
            cdt = "D3310"
        elif tooth_type == "Premolar":
            cdt = "D3320"
        elif tooth_type == "Molar":
            cdt = "D3330"

    fhir_output = build_fhir_resources(data, pulp_dx, apical_dx, treatment, cdt)

    return (
        pulp_dx,
        apical_dx,
        treatment,
        cdt,
        "\n".join(reasoning),
        json.dumps(fhir_output, indent=2)
    )

import gradio as gr

custom_css = """
body {
    background: linear-gradient(to bottom, #eaf2fb, #f5f9ff);
    font-family: 'Segoe UI', sans-serif;
}

.section-card {
    background-color: white;
    padding: 22px;
    border-radius: 10px;
    box-shadow: 0 4px 12px rgba(0, 70, 140, 0.08);
    margin-bottom: 22px;
}

h1 {
    color: #0b3c6f;
    font-weight: 600;
}

h3 {
    color: #174ea6;
    font-weight: 500;
}

button {
    background-color: #174ea6 !important;
    color: white !important;
    border-radius: 8px !important;
    font-weight: 600 !important;
    padding: 8px 16px !important;
}

textarea, input, select {
    border-radius: 6px !important;
}
"""

with gr.Blocks(css=custom_css, theme=gr.themes.Base()) as demo:

    gr.Markdown("""
    # CDS – Endodontics
    Clinical Decision Support System
    Evidence Based Dentistry
    ---
    """)

    with gr.Group(elem_classes="section-card"):
        gr.Markdown("### Patient & Pulpal Assessment")

        age_input = gr.Number(label="Age")
        tooth_input = gr.Dropdown(
            choices=[i for i in range(1,33)],
            label="Tooth (ADA Universal Numbering)"
        )

        endo_ice_input = gr.Dropdown(
            choices=["Positive", "Negative"],
            label="Endo Ice Test"
        )

        lingering_input = gr.Checkbox(label="Lingering Pain (>30 seconds)")
        caries_input = gr.Checkbox(label="Caries Extending into Pulp")
        prev_init_input = gr.Checkbox(label="Previously Initiated Therapy")
        prev_treated_input = gr.Checkbox(label="Previously Treated (Completed RCT)")
        control_input = gr.Checkbox(label="Control Tooth Responds Normally")

    with gr.Group(elem_classes="section-card"):
        gr.Markdown("### Apical Assessment")

        percussion_input = gr.Checkbox(label="Percussion Pain")
        swelling_input = gr.Checkbox(label="Swelling Present")
        sinus_input = gr.Checkbox(label="Sinus Tract Present")
        radiolucency_input = gr.Checkbox(label="Periapical Radiolucency")
        radiopacity_input = gr.Checkbox(label="Periapical Radiopacity")

    gr.Markdown("---")

    btn = gr.Button("Run Clinical Decision Support")

    with gr.Group(elem_classes="section-card"):
        gr.Markdown("### Diagnosis")
        output_pulp = gr.Textbox(label="Pulpal Diagnosis")
        output_apical = gr.Textbox(label="Apical Diagnosis")

    with gr.Group(elem_classes="section-card"):
        gr.Markdown("### Treatment Plan")
        output_treatment = gr.Textbox(label="Recommended Treatment")
        output_cdt = gr.Textbox(label="Suggested CDT Code")

    with gr.Group(elem_classes="section-card"):
        gr.Markdown("### Clinical Reasoning")
        output_reasoning = gr.Textbox(lines=4)

    with gr.Group(elem_classes="section-card"):
        gr.Markdown("### FHIR Structured Output")
        output_fhir = gr.Code(language="json")

    gr.Markdown("""
    ---
    This prototype Clinical Decision Support System is developed for academic purposes only
    and is not intended for independent clinical decision-making.
    """)

    btn.click(
        structured_process_input,
        inputs=[
            age_input,
            tooth_input,
            endo_ice_input,
            lingering_input,
            caries_input,
            prev_init_input,
            prev_treated_input,
            control_input,
            percussion_input,
            swelling_input,
            sinus_input,
            radiolucency_input,
            radiopacity_input
        ],
        outputs=[
            output_pulp,
            output_apical,
            output_treatment,
            output_cdt,
            output_reasoning,
            output_fhir
        ]
    )

demo.launch(server_name="0.0.0.0", server_port=7860)
